DISK_FILE = "disco_general.bin"

PAGE_SIZE = 4096  # 4 KB
DATA_DIR = "disk" 
ORDER = 4  # Grado del �rbol B+

# CONFIGURACI�N DEL DISCO
PLATOS = 2
PISTAS = 3
SECTORES_POR_PISTA = 4
BYTES_POR_SECTOR = 5

TOTAL_DE_BYTES = 240
