PAGE_SIZE = 4096  # 4 KB
DATA_DIR = "disk" 
ORDER = 4  # Grado del árbol B+

#CONFIGURACIÓN DEL DISCO

PLATOS = 2
PISTAS = 10
SECTORES_POR_PISTA = 8
BYTES_POR_SECTOR = 4096  #bytes

TOTAL_DE_BYTES = PLATOS*2 * PISTAS * SECTORES_POR_PISTA * BYTES_POR_SECTOR 